name: Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build \
            -t gcp-platform-app:latest \
            ./app

      - name: Verify Docker Image
        run: docker images gcp-platform-app